name: hoge test
description: aaa
title: ccc
labels: ddd
assignees: eee

body:
  - type: input
    attributes:
      label: hoge01
    validations:
      required: true
  - type: textarea
    attributes:
      label: 備考
