name: hoge test
description: aaa
title: Issue title
labels: ddd
assignees: eee

body:
  - type: input
    id: aaa
    attributes:
      label: hoge01
      description: ggg
    validations:
      required: true
  - type: input
    id: bbb
    attributes:
      placeholder: hhh
      label: hoge02
      value: iii
      description: ggg
  - type: dropdown
    id: ddd
    attributes:
      label: Issue type
      options:
        - a
        - b
        - c
        - d
        - e
      description: select! 111
  - type: dropdown
    id: ddd2
    attributes:
      label: Issue type
      options:
        - a
        - b
        - c
        - d
        - e
      description: select! 222
      multiple: true
  - type: checkboxes
    id: check01
    attributes:
      label: Issue type
      options:
        - label: 本当に？
          requred: true
      description: check!
  - type: textarea
    id: ccc
    attributes:
      label: 備考
