name: hoge test
description: aaa
title: ccc
labels: ddd
assignees: eee

body:
  - type: input
    id: 1
    attributes:
      label: hoge01
    validations:
      required: true
  - type: input
    id: 2
    attributes:
      description: ggg
      placeholder: hhh
      label: hoge02
      value: iii
  - type: textarea
    id: 3
    attributes:
      label: 備考
