name: hoge test
description: aaa
title: ccc
labels: ddd
assignees: eee

body:
  - type: input
    id: aaa
    attributes:
      label: hoge01
    validations:
      required: true
  - type: input
    attributes:
      id: 2
      description: ggg
      placeholder: hhh
      label: hoge02
      value: iii
  - type: textarea
    attributes:
      id: 3
      label: 備考
